In [2]:
from importlib import import_module

from torch.utils.data import DataLoader

from train_eval import test
from utils import CustomDataset, DataConfig

In [3]:
def call(model_path, model_name='TextCNN', dataset='ship_data',
         embedding='embedding.npz'):
    model_module = import_module(f'models.{model_name}')
    model_config = model_module.Config()
    data_config = DataConfig(dataset, embedding)
    test_dataset = CustomDataset(data_config, data_class='test')
    test_loader = DataLoader(test_dataset, batch_size=model_config.batch_size)

    model = model_module.Model(model_config, data_config).to(data_config.device)

    test(data_config, model, test_loader, model_path)

In [5]:
call(model_path='./result/TextCNN_2embedding_not_freezze.ckpt')

Test Loss:   0.2,  Test Acc: 93.70%
Precision, Recall and F1-Score...
              precision    recall  f1-score   support

        散杂货船     0.9066    0.9510    0.9282     44333
          渔船     0.9726    0.9852    0.9788     40276
        集装箱船     0.9317    0.9120    0.9217     18656
          油船     0.9568    0.7894    0.8651      6458
       液体散货船     0.9280    0.7449    0.8264      5919

    accuracy                         0.9370    115642
   macro avg     0.9391    0.8765    0.9041    115642
weighted avg     0.9375    0.9370    0.9361    115642

Confusion Matrix...
[[42160   897   961   139   176]
 [  559 39678    20     9    10]
 [ 1520    59 17014     6    57]
 [ 1139    93    29  5098    99]
 [ 1127    70   237    76  4409]]
