In [3]:
from importlib import import_module

from torch.utils.data import DataLoader

from train_eval import test
from utils import CustomDataset, DataConfig

import torch

In [9]:
def call(model_path, model_name='TextCNN', dataset='ship_data',
         embedding='embedding.npz'):
    model_module = import_module(f'models.{model_name}')
    model_config = model_module.Config()
    data_config = DataConfig(dataset, embedding)
    test_dataset = CustomDataset(data_config, data_class='test')
    test_loader = DataLoader(test_dataset, batch_size=model_config.batch_size)
    model = model_module.Model(model_config, data_config).to(data_config.device)
    test(data_config, model, test_loader, model_path)

In [10]:
call(model_path='./result/TextCNN_单层嵌入层.ckpt')

Test Loss:  0.19,  Test Acc: 93.92%
Precision, Recall and F1-Score...
              precision    recall  f1-score   support

        散杂货船     0.9092    0.9528    0.9305     44333
          渔船     0.9736    0.9855    0.9795     40276
        集装箱船     0.9330    0.9157    0.9243     18656
          油船     0.9562    0.8018    0.8722      6458
       液体散货船     0.9420    0.7466    0.8330      5919

    accuracy                         0.9392    115642
   macro avg     0.9428    0.8805    0.9079    115642
weighted avg     0.9398    0.9392    0.9383    115642

Confusion Matrix...
[[42240   862   950   141   140]
 [  552 39691    15    12     6]
 [ 1461    59 17084     6    46]
 [ 1080    88    32  5178    80]
 [ 1127    66   229    78  4419]]
